apiVersion: v2
name: nifi-registry
description: A Helm chart for Apache NiFi Registry - A centralized storage & management solution for versioned flows
type: application
version: 1.0.0
appVersion: "2.4.0"
home: https://nifi.apache.org/registry
sources:
  - https://github.com/apache/nifi-registry
keywords:
  - nifi
  - registry
  - dataflow
  - apache
  - workflow
annotations:
  category: Analytics
  license: Apache-2.0