# Minimal test configuration for NiFi Registry
# Uses all defaults, no custom configuration files

replicaCount: 1

image:
  repository: apache/nifi-registry
  tag: "2.4.0"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 18080

# Security disabled
security:
  enabled: false

# Persistence disabled for testing
persistence:
  enabled: false

# Resource limits for testing
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# NiFi Registry configuration
nifiRegistry:
  web:
    httpPort: 18080
    httpsPort: 18443
  jvm:
    heapSize: "512m"
  # No custom properties - use all defaults
  properties: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000

# ServiceAccount
serviceAccount:
  create: true

# Ingress disabled
ingress:
  enabled: false 