{{- if and .Values.security.enabled .Values.oidc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nifi-registry.fullname" . }}-authorizers
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
data:
  authorizers.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <authorizers>
        <!-- Composite Authorizer -->
        <authorizer>
            <identifier>managed-authorizer</identifier>
            <class>org.apache.nifi.registry.security.authorization.CompositeConfigurableUserGroupProvider</class>
            <property name="User Group Provider">composite-user-group-provider</property>
            <property name="Access Policy Provider">file-access-policy-provider</property>
        </authorizer>

        <!-- Composite User Group Provider -->
        <userGroupProvider>
            <identifier>composite-user-group-provider</identifier>
            <class>org.apache.nifi.registry.security.authorization.CompositeConfigurableUserGroupProvider</class>
            <property name="User Group Provider 1">file-user-group-provider</property>
        </userGroupProvider>

        <!-- File User Group Provider -->
        <userGroupProvider>
            <identifier>file-user-group-provider</identifier>
            <class>org.apache.nifi.registry.security.authorization.FileUserGroupProvider</class>
            <property name="Users File">./conf/users.xml</property>
            <property name="Legacy Authorized Users File"></property>
            <property name="Initial User Identity 1">admin</property>
        </userGroupProvider>

        <!-- File Access Policy Provider -->
        <accessPolicyProvider>
            <identifier>file-access-policy-provider</identifier>
            <class>org.apache.nifi.registry.security.authorization.FileAccessPolicyProvider</class>
            <property name="User Group Provider">composite-user-group-provider</property>
            <property name="Authorizations File">./conf/authorizations.xml</property>
            <property name="Initial Admin Identity">admin</property>
            <property name="Legacy Authorized Users File"></property>
            <property name="Node Identity 1"></property>
        </accessPolicyProvider>
    </authorizers>
{{- end }} 