apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-registry.fullname" . }}
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.security.enabled }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nifiRegistry.web.httpsPort }}
      protocol: TCP
      name: https
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nifiRegistry.web.httpPort | default 18080 }}
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "nifi-registry.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-registry.fullname" . }}-headless
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- if .Values.security.enabled }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nifiRegistry.web.httpsPort }}
      protocol: TCP
      name: https
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nifiRegistry.web.httpPort | default 18080 }}
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "nifi-registry.selectorLabels" . | nindent 4 }}